services:
  - type: web
    name: rudrabot
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential
      pip install -r requirements.txt
    startCommand: python main.py
    plan: free
